spring:
  redis:
    host: localhost
    port: 6376
    database: 0
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/authentication
      username: root
      password: root
server:
  port: 8060